print("Welcome to Brand Name Generator")
city_name=input("Whats's name of the city you grew up in?")
print(city_name)
pet_name=input("Whats's your pet's name?")
print(pet_name)
print("Your band name could be "+ city_name + " " + pet_name )